image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
  artifacts:
    paths:
      - .public
  only:
    - main  # oder master, je nachdem wie dein Hauptbranch heißt
