image: node:20-alpine

stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r * public/
    - rm -rf public/.gitlab-ci.yml public/.git/
  artifacts:
    paths:
      - public
  only:
    - main
