image: alpine:latest

stages:
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

pages:
  stage: deploy
  script:
    # Ordner für GitLab Pages erstellen
    - mkdir public
    - cp -r * public/
    - rm -rf public/.git public/.gitlab-ci.yml
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
