image: alpine:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    # Ordner für GitLab Pages erstellen
    - mkdir public
    # Alle Dateien kopieren
    - cp -r * public/
    # GitLab-spezifische Dateien entfernen
    - rm -rf public/.git public/.gitlab-ci.yml
  artifacts:
    paths:
      - public
  only:
    - main
